export const dummyDatas = [
  {
    name: "David",
    email: "david@gmail.com",
    age: 24,
    role: "admin",
    status: "Active",
    date: "2024-08-01",
  },
  {
    name: "Joe",
    email: "joe@gmail.com",
    age: 23,
    role: "user",
    status: "Active",
    date: "2024-08-03",
  },
  {
    name: "Brad",
    email: "brad@gmail.com",
    age: 26,
    role: "admin",
    status: "Active",
    date: "2024-08-07",
  },
  {
    name: "Patrick",
    email: "patrick@gmail.com",
    age: 24,
    role: "admin",
    status: "Active",
    date: "2024-08-10",
  },
  {
    name: "Adam",
    email: "adam@gmail.com",
    age: 24,
    role: "admin",
    status: "Active",
    date: "2024-08-12",
  },
  {
    name: "Jason",
    email: "jason@gmail.com",
    age: 24,
    role: "admin",
    status: "Active",
    date: "2024-08-15",
  },
  {
    name: "Patrick",
    email: "patrick@gmail.com",
    age: 24,
    role: "admin",
    status: "Active",
    date: "2024-08-18",
  },
  {
    name: "Adam",
    email: "adam@gmail.com",
    age: 24,
    role: "admin",
    status: "Active",
    date: "2024-08-20",
  },
  {
    name: "Jason",
    email: "jason@gmail.com",
    age: 24,
    role: "admin",
    status: "Active",
    date: "2024-08-22",
  },
  {
    name: "Patrick",
    email: "patrick@gmail.com",
    age: 24,
    role: "admin",
    status: "Active",
    date: "2024-08-25",
  },
  {
    name: "Adam",
    email: "adam@gmail.com",
    age: 24,
    role: "admin",
    status: "Active",
    date: "2024-08-28",
  },
  {
    name: "Jason",
    email: "jason@gmail.com",
    age: 24,
    role: "admin",
    status: "Active",
    date: "2024-08-30",
  },
  {
    name: "Patrick",
    email: "patrick@gmail.com",
    age: 24,
    role: "admin",
    status: "Active",
    date: "2024-09-01",
  },
  {
    name: "Adam",
    email: "adam@gmail.com",
    age: 24,
    role: "admin",
    status: "Active",
    date: "2024-09-03",
  },
  {
    name: "Jason",
    email: "jason@gmail.com",
    age: 24,
    role: "admin",
    status: "Active",
    date: "2024-09-05",
  },
  {
    name: "Patrick",
    email: "patrick@gmail.com",
    age: 24,
    role: "admin",
    status: "Active",
    date: "2024-09-07",
  },
  {
    name: "Adam",
    email: "adam@gmail.com",
    age: 24,
    role: "admin",
    status: "Active",
    date: "2024-09-10",
  },
  {
    name: "Jason",
    email: "jason@gmail.com",
    age: 24,
    role: "admin",
    status: "Active",
    date: "2024-09-12",
  },
  {
    name: "Patrick",
    email: "patrick@gmail.com",
    age: 24,
    role: "admin",
    status: "Active",
    date: "2024-09-15",
  },
  {
    name: "Adam",
    email: "adam@gmail.com",
    age: 24,
    role: "admin",
    status: "Active",
    date: "2024-09-18",
  },
  {
    name: "Jason",
    email: "jason@gmail.com",
    age: 24,
    role: "admin",
    status: "Active",
    date: "2024-09-20",
  },
  {
    name: "Patrick",
    email: "patrick@gmail.com",
    age: 24,
    role: "admin",
    status: "Active",
    date: "2024-09-22",
  },
  {
    name: "Adam",
    email: "adam@gmail.com",
    age: 24,
    role: "admin",
    status: "Active",
    date: "2024-09-25",
  },
  {
    name: "Jason",
    email: "jason@gmail.com",
    age: 24,
    role: "admin",
    status: "Active",
    date: "2024-09-28",
  },
];
